name: Android UI Tests

on: pull_request

jobs:
  android-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          system-image: system-images;android-30;google_apis;x86
          api-level: 29
          script: ./gradlew clean app:connectedCheck